server:
  port: 8000

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  #最大上传文件大小
  http:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



